language: python
sudo: false
dist: trusty
services:
- docker
cache:
  directories:
  - "$HOME/.cache/pip"
stages:
  - test
  - name: deploy
    # require any tag name to deploy
    if: tag =~ .*
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsnappy-dev
_install: &_install
  - gimme 1.8
  - source ~/.gimme/envs/latest.env
  - pip install --upgrade pip
  - pip install tensorflow
  - pip install -r requirements.txt codecov
  - pip install -e .
_coverage: &_coverage
  - SCRIPT="coverage run --concurrency=multiprocessing -m unittest discover && coverage combine"
_deploy: &_deploy
  provider: script
  script: twine upload dist/*py3-none-any* -u $PYPI_LOGIN -p $PYPI_PASS
  skip_cleanup: true
  on:
    tags: true
matrix:
  include:
    - python: 3.4
      env: *_coverage
      install: *_install
    - python: 3.5
      env: *_coverage
      install: *_install
    - python: 3.6
      env: SCRIPT="pycodestyle --max-line-length=99 --ignore E252,E121,E123,E126,E226,E24,E704,W503,W504 ."
      install: pip install pycodestyle
    - python: 3.6
      env: *_coverage
      install: *_install
      after_success:
        - codecov
    - stage: deploy
      python: 3.4
      install:
        - pip3 install --upgrade pip
        - pip3 install twine
      before_script: skip
      script:
        - python3 setup.py bdist_wheel
      deploy: *_deploy
  fast_finish: true
before_script:
  - docker run -d --privileged -p 9432:9432 --name bblfshd bblfsh/bblfshd
  - docker exec -it bblfshd bblfshctl driver install python bblfsh/python-driver
script:
  - (eval "$SCRIPT")
notifications:
  email: false
